import time
from datetime import datetime

def get_greeting():
    current_hour = datetime.now().hour
    if 5 <= current_hour < 12:
        return "Доброе утро"
    elif 12 <= current_hour < 18:
        return "Добрый день"
    elif 18 <= current_hour < 23:
        return "Добрый вечер"
    else:
        return "Доброй ночи"

def generate_github_profile():
    greeting = get_greeting()
    message = f"{greeting}! Я рад вас приветствовать на своём профиле GitHub!"
    
    animated_message = ""
    for char in message:
        animated_message += char
        print(f"\033[1;32m{animated_message}\033[0m")
        time.sleep(0.1)

if __name__ == "__main__":
    generate_github_profile()

